# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thanks for opening your first issue here! Please follow the issue template to help us help you ğŸ‘ğŸ‰ğŸ˜„
  If you have screenshots to share demonstrating the issue, that's really helpful! ğŸ“¸ You can [make a gif](https://www.cockos.com/licecap/) too!
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
 Thanks for opening this pull request! `Dangerbot` will test out your code and reply in a bit with some pointers and requests.
 There may be some errors, **but don't worry!** We're here to help! ğŸ‘ğŸ‰ğŸ˜„
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
 Congrats on merging your first pull request! ğŸ™ŒğŸ‰âš¡ï¸ 
 Your code will likely be published to https://mapknitter.org in the next few days. 
 In the meantime, can you tell us your Twitter handle so we can thank you properly?
 Now that you've completed this, you can help someone else take their first step!
 Reach out to someone else working on theirs on [Public Lab's code welcome page](https://code.publiclab.org#r=all). Thanks!
 <details>
 <summary><b>Help others take their first step</b></summary>
 <p>Now that you've merged your first pull request, you're the perfect person to help someone else out with this challenging first step. ğŸ™Œ </p>
 <p><a href="https://code.publiclab.org#r=all">https://code.publiclab.org</a></p>
 <p>Try looking at this list of `first-timers-only` issues, and see if someone else is waiting for feedback, or even stuck! ğŸ˜• </p>
 <p>People often get stuck at the same steps, so you might be able to help someone get unstuck, or help lead them to some documentation that'd help. Reach out and be encouraging and friendly! ğŸ˜„ ğŸ‰ </p>
 <p>Read about <a href="https://github.com/publiclab/plots2/issues/3458">how to help support another newcomer here</a>, or find <a href="https://github.com/publiclab/plots2/labels/support">other ways to offer mutual support here</a>.</p>
 </details>

# It is recommended to include as many gifs and emojis as possible
