sudo: required

language: generic

services:
  - docker

install:
  - cp config/database.yml.test.example config/database.yml
  - cp config/config.yml.example config/config.yml
  - cp db/schema.rb.example db/schema.rb
  - docker-compose -f docker-compose.test.yml up -d --build
  - >
    while (! docker logs mapknitter-test | grep "Phusion Passenger Standalone web server started") > /dev/null 2>&1; do
      echo "Waiting for start script to finish...";
      sleep 20;
    done; echo "Done!"
  - docker-compose -f docker-compose.test.yml exec web bash -lc "rake db:setup || rake db:migrate"

env:
  global:
    - RAILS_ENV=test
  matrix:
    - TASK="CI=true TRAVIS=true rake test:unit"
    - TASK="CI=true TRAVIS=true rake test:integration"
    - TASK="CI=true TRAVIS=true rake test:functional"
    - TASK="CI=true TRAVIS=true rake assets:precompile"
<<<<<<< HEAD
=======
    - TASK="CI=true TRAVIS=true bundle exec rubocop
>>>>>>> 22e5312e... Fix gemfile.lock

script:
  - docker-compose -f docker-compose.test.yml exec web bash -lc "$TASK"
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - main
    - unstable

