language: ruby
rvm:
  - 2.4.6

services:
  - mysql
  - docker

cache:
  bundler: true
  directories:
   - public/lib/

install:
  - cp config/database.yml.example config/database.yml
  - cp config/config.yml.example config/config.yml
  - cp db/schema.rb.example db/schema.rb
  - ./lib/exporter-deps.sh > /dev/null 2>&1
  - bundle install && yarn install
  - if [ $RAILS_ENV != 'production' ]; then
    bundle exec rake db:setup || bundle exec rake db:migrate ;
    fi

env:
  global:
    - RAILS_ENV=test
    - CI=true
    - TRAVIS=true

jobs:
  include:
    - name: "Unit Tests"
      script: bundle exec rake test:unit
    - name: "Integration Tests"
      script: bundle exec rake test:integration
    - name: "Functional Tests"
      script: bundle exec rake test:functional
    - name: "Rubocop Linter"
      script: bundle exec rubocop
    - name: "Docker Builds"
      script: docker build -t mapknitter .
    - name: "Asset Precompilation"
      env:
        - RAILS_ENV=production
      script: bundle exec rake assets:precompile

branches:
  only:
    - main
    - unstable
    - development

