version: '3.3'
services:
  db:
    container_name: db
    image: mysql:5.6
    env_file:
      - mapknitter.env
    volumes:
      - /srv/mapknitter_priv1/mk1_database:/var/lib/mysql
  web:
    container_name: web
    build: .
    env_file:
      - mapknitter.env
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  bundle_cache:
