version: '3.5'
services:
  db:
    container_name: db
    image: mysql:5.7
    env_file:
      - mapknitter.env
    volumes:
      - ../mysql:/var/lib/mysql
      - ../dump:/docker-entrypoint-initdb.d
  web:
    container_name: web
    build: .
    ulimits:
      core: 0
    env_file:
      - mapknitter.env
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - yarn_cache:/app/node_modules/
    ports:
      - $PORT:3000
    depends_on:
      - db

volumes:
  bundle_cache:
  yarn_cache:
