version: '3.3'
services:
  db:
    image: mysql:5.7
    env_file:
      - mapknitter.env
    volumes:
      - ../mysql:/var/lib/mysql
  web:
    build: .
    env_file:
      - mapknitter.env
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - bower_cache:/app/public/lib
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  bundle_cache:
  bower_cache:
