version: '3.3'
services:
  db:
    container_name: database
    image: mysql:5.7
    env_file:
      - mapknitter.env
    volumes:
      - ../mysql:/var/lib/mysql
      - ../dump:/docker-entrypoint-initdb.d
  web:
    container_name: mapknitter
    build: .
    env_file:
      - mapknitter.env
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - yarn_cache:/app/public/lib
    ports:
      - $PORT:3000
    depends_on:
      - db

volumes:
  bundle_cache:
  yarn_cache:
